config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  resources :users
  resources :events

  resources :registrations, except: [:update, :edit, :destroy]

  root 'welcome#index'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
end

app/models/event.rb
class Event < ActiveRecord::Base
  require'open-uri'
  validates :name, :location, :start_time, :user_id, presence: true

  has_many :registrations
  has_many :users, through: :registrations

  belongs_to :owner, :class_name => "User", :foreign_key => "user_id"

  def directions_link
    location.sub(' ', '+')
  end

  def date
    start_time.strftime("%a, %B %e %Y")
  end

  def time
    start_time.strftime("%I:%M %p")
  end

  def share_text
    URI::encode("I'm going to #{name}! Meet me there? https://spoon-events.herokuapp.com/events/#{id}")
  end

end

app/models/registration.rb
class Registration < ActiveRecord::Base
  validates :user_id, :event_id, presence: true

  belongs_to :user
  belongs_to :event
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates_presence_of :password, :on => :create
  validates :name, presence: true
  validates :email, presence: true, uniqueness: true

  has_many :registrations
  has_many :events, through: :registrations
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def require_login
    unless current_user
      flash[:info] = "You must be logged in to view this page."
      redirect_to login_path
    end
  end

  def require_owner
    @event = Event.find(params[:id])
    unless current_user = @event.owner
      redirect_to @event
    end
  end

  def past_events
    past_events ||= current_user.events.where('start_time <= ?', Date.today)
  end

  def future_events
    future_events ||= current_user.events.where('start_time >= ?', Date.today)
  end

  def all_future_events
    all_future_events ||= Event.where('start_time >= ?', Date.today)
  end

  def owned_events
    owner_events ||= current_user.events
  end

  helper_method :current_user
  helper_method :require_login
  helper_method :require_owner
  helper_method :past_events
  helper_method :future_events
  helper_method :owned_events
  helper_method :all_future_events
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :require_login, only: [:create, :edit, :new]
  before_action :require_owner, only: [:edit, :destroy]

  def index
    @events = Event.all
  end

  def new
    @event = Event.new
  end

  def edit
    @event = Event.find(params[:id])
  end

  def create
    @event = Event.new(event_params)
    @event.user_id = current_user.id
    if @event.save
      flash[:success] = "Your event was successfully created!"
      redirect_to @event
    else
      flash[:danger] = "There was an error creating your event."
      render :new
    end
  end

  def update
    @event = Event.find(params[:id])
    if @event.update(event_params)
      flash[:success] = "Your account was successfully updated!"
      redirect_to @event
    else
      flash[:danger] = "There was an error updating your account."
      render :edit
    end
  end

  def show
    @event = Event.find(params[:id])
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to root_path
  end

  private

  def event_params
    params.require(:event).permit(:name, :location, :start_time)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController

  def create
    @event = Event.find(params[:event_id])
    @user = User.find(params[:user_id])
    registration = @event.registrations.create(user_id: @user.id)
    if registration.save
      flash[:success] = "You're going to #{@event.name}!"
      redirect_to event_path(@event)
    else
      flash[:danger] = "There was an error creating your registration."
      render :new
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.find_by(email: params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user)
    else
      flash[:danger] = "Invalid Login"
      redirect_to root_path
    end
  end

  def destroy
    session.clear
    flash[:info] = "Logout Successful"
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_login, only: [:edit]

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Your account was successfully created!"
      session[:user_id] = @user.id
      redirect_to @user
    else
      flash[:danger] = "There was an error creating your account."
      render :new
    end
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      flash[:success] = "Your account was successfully updated!"
      session[:user_id] = @user.id
      redirect_to @user
    else
      flash[:danger] = "There was an error updating your account."
      render :edit
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    session.clear
    flash[:info] = "Your account was successfully deleted. Sad to see you go!"
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def bootstrap_class_for flash_type
    { success: "alert-success", error: "alert-danger", alert: "alert-warning", notice: "alert-info" }[flash_type] || flash_type.to_s
  end

  def flash_messages(opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "alert alert-#{bootstrap_class_for(msg_type)} fade in") do
              concat content_tag(:button, 'x', class: "close", data: { dismiss: 'alert' })
              concat message
            end)
    end
    nil
  end

end

app/views/events/_click_to_tweet.html.erb
<a class="btn btn-lg btn-info btn-fill"
       href="https://twitter.com/intent/tweet?text=<%= @event.share_text%>"
       data-size="large"
       data-count="none"
       target="_blank"><i class="fa fa-twitter"></i> Tell Your Friends</a>

app/views/events/_form.html.erb
<%= render 'location_search' %>

<%= form_for @event do |f| %>

  <p>
    <%= f.text_field :name, placeholder: "Event Name", size: 50 %>
  </p>

  <p>
    <%= f.text_field :location, placeholder: "Location", id: 'searchTextField', size: 50 %>
  </p>

  <p>
    <%= f.datetime_select :start_time, :ampm => true, :minute_step => 15 %>
  </p>

  <p>
    <%= f.submit class: "btn btn-lg btn-success btn-fill" %>
  </p>

<% end %>

app/views/events/_location_search.html.erb
<script>
function initialize() {

var input = document.getElementById('searchTextField');
var autocomplete = new google.maps.places.Autocomplete(input);
}

google.maps.event.addDomListener(window, 'load', initialize);
</script>

app/views/events/_owner_tools.html.erb
<% if current_user && @event.owner = current_user %>
<div class="well well-sm text-center">
  <h4>Admin Tools</h4>
  <%= link_to "Edit Event", edit_event_path(@event), class: "btn btn-info btn-fill" %>
  <%= link_to 'Permanently Delete Event',  { action: :destroy, id: @event.id }, method: :delete, class: "btn btn-danger btn-fill", data: { confirm: 'Are you sure?' } %>
</div>
<% end %>

app/views/events/_registrations.html.erb
<% if @event.users.empty? %>
<h3 class="text-center">No Attendees Just Yet!</h3>
<% else %>
<h3 class="text-center">Attendees: <%= @event.users.count %></h3>

<div class="table-responsive">
  <table class="table table-hover">
    <tr>
      <th>#</th>
      <th>Name</th>
    </tr>
    <% @event.users.each_with_index do |attendee, index| %>
    <tr>
      <td><%= index + 1 %></td>
      <td><%= attendee.name %></td>
    </tr>
    <% end %>
  </table>
</div>
<% end %>

app/views/events/_rsvp.html.erb
<% if current_user && current_user.events.include?(@event) %>
<button type="button" class="btn btn-success btn-lg btn-fill active">You're Going!</button>
<%= render 'click_to_tweet' %>
<% elsif current_user %>
<%= link_to "Attend Event", registrations_path(:user_id => current_user.id, :event_id => @event.id), :method => :post, class: "btn btn-lg btn-fill btn-success" %>
<% else %>
<%= link_to "Sign Up to Attend", new_user_path, class: "btn btn-lg btn-info btn-fill" %>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form' %>

app/views/events/index.html.erb
<h1>All Upcoming Events</h1>

<div class="row">
  <% all_future_events.each do |event| %>
  <div class="col-sm-6 col-md-4">
    <div class="thumbnail">
      <div class="caption">
        <h3 class="text-center"><%= event.name %></h3>
        <p><b>Date:</b> <%= event.date %> </p>
        <p><b>Time:</b> <%= event.time %> </p>
        <p><b>Location:</b> <%= event.location %> </p>
        <div class="text-center">
          <%= link_to "RSVP Here!", event_path(event), class: "btn btn-lg btn-primary btn-fill" %>
        </div>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/events/new.html.erb
<h1>Create New Event</h1>

<%= render 'form' %>

app/views/events/show.html.erb
<div class="row">
  <div class="col-md-6">
    <h1><%= @event.name %></h1>
    <h4>Organized by <%= @event.owner.name %></h4>
    <%= render 'owner_tools' %>
    <h3><%= @event.location.titleize %></h3>
    <p> <a href="https://www.google.com/maps/dir//<%= @event.directions_link %>" target="_blank">Get Directions </a></p>
    <p><b>Date:</b> <%= @event.date %> </p>
    <p><b>Time:</b> <%= @event.time %> </p>

    <%= render 'rsvp' %>

  </div>
  <div class="col-md-6">
    <%= render 'registrations' %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <title>Spoon Events</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => false %>
  <%= stylesheet_link_tag '//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css' %>
  <%= stylesheet_link_tag '//fonts.googleapis.com/css?family=Grand+Hotel|Open+Sans:400,300' %>

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => false %>
  <%= javascript_include_tag "//google-code-prettify.googlecode.com/svn/loader/run_prettify.js" %>
  <!-- <link href='https://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'> -->
  <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&libraries=places"></script>
  <%= csrf_meta_tags %>
  <%= yield :style %>
</head>
<body data-features="<%= yield :features %>" class="<%= yield :class %>">
  <div class="container">
    <%= render partial: 'shared/nav' %>

    <%= flash_messages %>

    <%= yield %>

  </div>
</body>
</html>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <% if current_user %>
          <%= link_to "Spoon Events", events_path, class: 'navbar-brand' %>
      <% else %>
          <%= link_to "Spoon Events", root_path, class: 'navbar-brand' %>
      <% end %>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Upcoming Events", events_path %></li>
        <li><%= link_to "Organize an Event", new_event_path %> </li>
     </ul>

      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
            <li><%= link_to current_user.name, user_path(current_user) %>  </li>
            <li><%= link_to "Logout", logout_path, method: 'delete' %></li>
        <% else %>
            <%= form_for(:session, url: login_path, html: {class: "navbar-form"}) do |f| %>

                <%= f.label :email %>
                <%= f.email_field :email, class: 'form-control' %>

                <%= f.label :password %>
                <%= f.password_field :password, class: 'form-control' %>

                <%= f.submit "Login", class: "btn btn-primary btn-fill" %>
            <% end %>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/users/_form.html.erb
<div class="container text-center">

  <div class="row">
    <div class="col-md-5 col-md-offset-4">
      <%= form_for @user do |f| %>
          <div class="form-group">
            <%= f.text_field :name, placeholder: "name", class: "form-control" %><br>

            <%= f.text_field :email, placeholder: "email", class: "form-control" %><br>

            <%= f.password_field :password, placeholder: "password", class: "form-control" %><br>

            <%= f.password_field :password_confirmation, placeholder: "confirm password", class: "form-control" %><br>

            <%= f.submit class: "btn btn-lg btn-success" %>
          </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/_future_events.html.erb
<% unless future_events.empty? %>
<h3>Events You're Attending</h3>
<div class="row">
  <% future_events.each do |event| %>
  <div class="col-sm-6 col-md-4">
    <div class="thumbnail">
      <div class="caption">
        <h3 class="text-center"><%= event.name %></h3>
        <p><b>Date:</b> <%= event.date %> </p>
        <p><b>Time:</b> <%= event.time %> </p>
        <p><b>Location:</b> <%= event.location %> </p>
        <div class="text-center">
          <%= link_to "RSVP Here!", event_path(event), class: "btn btn-primary" %>
        </div>
      </div>
    </div>
  </div>
  <% end %>
</div>
<% end %>

app/views/users/_owned_events.html.erb
<% unless owned_events.empty? %>
<h3>Events You've Organized</h3>
<div class="row">
  <% owned_events.each do |event| %>
  <div class="col-sm-6 col-md-4">
    <div class="thumbnail">
      <div class="caption">
        <h3 class="text-center"><%= event.name %></h3>
        <p><b>Date:</b> <%= event.date %> </p>
        <p><b>Time:</b> <%= event.time %> </p>
        <p><b>Location:</b> <%= event.location %> </p>
        <div class="text-center">
          <%= link_to "RSVP Here!", event_path(event), class: "btn btn-primary" %>
        </div>
      </div>
    </div>
  </div>
  <% end %>
</div>
<% end %>

app/views/users/_past_events.html.erb
<% unless past_events.empty? %>
<h3>Events You've Attended</h3>
<div class="row">
  <% past_events.each do |event| %>
  <div class="col-sm-6 col-md-4">
    <div class="thumbnail">
      <div class="caption">
        <h3 class="text-center"><%= event.name %></h3>
        <p><b>Date:</b> <%= event.date %> </p>
        <p><b>Time:</b> <%= event.time %> </p>
        <p><b>Location:</b> <%= event.location %> </p>
        <div class="text-center">
          <%= link_to "RSVP Here!", event_path(event), class: "btn btn-primary" %>
        </div>
      </div>
    </div>
  </div>
  <% end %>
</div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

app/views/users/new.html.erb
<h1>Create New User</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<h1><%= @user.name %>
  <%= link_to "Edit Profile", edit_user_path(@user), class: "btn btn-info" %>
  <%= link_to 'Permanently Delete Account',  { action: :destroy, id: @user.id }, method: :delete, class: "btn btn-danger", data: { confirm: 'Are you sure?' } %> </h1>

<%= render 'owned_events' %>

<%= render 'future_events' %>

<%= render 'past_events' %>

app/views/welcome/index.html.erb
<div class="jumbotron text-center">
  <h1>Welcome to Spoon Events!</h1>
  <p>Attend events created by Spoon campus reps or organize your own!</p>
  <%= link_to "Sign Me Up!", new_user_path, class: "btn btn-lg btn-info btn-fill" %>
</div>